language: go
sudo: false
go:
  - 1.8
  - 1.9
  - tip
install:
  - go get -v github.com/golang/lint/golint
  - go get -v github.com/casbin/casbin
  - go get -v github.com/samuel/go-zookeeper/zk
script:
  - go vet ./...
  - $HOME/gopath/bin/golint .